### ISSUE TITLE
upgrading from 4.7.0 to 4.8.0 breaks symbol to proc callbacks

### ISSUE THREAD

**Issue by BM5k** [thoughtbot/factory_girl#980]
This factory works as expected on 4.7.0
```
FactoryGirl.define do
  factory :unconfirmed_user, class: 'User' do
    email                 { Faker::Internet.email }
    password              { Faker::Internet.password }
    password_confirmation { password }

    factory :user, aliases: %i[ confirmed_user ] do
      after :create, &:confirm
    end
  end
end
```
but causes the following output after upgrading to 4.8.0:

```
 NoMethodError:
       undefined method `confirm' for #<FactoryGirl::SyntaxRunner:0x007feab1f28700>
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/callback.rb:13:in `instance_exec'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/callback.rb:13:in `run'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/callbacks_observer.rb:11:in `block in update'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/callbacks_observer.rb:10:in `each'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/callbacks_observer.rb:10:in `update'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:20:in `notify'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:13:in `block in result'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
     # /Users/bm5k/.rvm/gems/ruby-2.4.0@disproxary/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
```

**Comment by fujimura** [comment]
There's a bug in instance_exec with symbol.to_proc in Ruby 2.4.0.

[Bug #13074: When executing instance_exec with symbol.to_proc, it ignores first argument.](https://bugs.ruby-lang.org/issues/13074)

**Comment by BM5k** [comment]
Confirmed that this is _not_ a problem with factory girl ~> 4.8.0 + ruby 2.3.3.

@fujimura thanks for pointing this out
